name: Test/Deploy Master

on:
  push:
    branches: ['development']

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: Eslint check
        run: yarn run lint

  deploy-docs:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Developer Event
        uses: peter-evans/repository-dispatch@main
        with:
          token: ${{ secrets.DOCS_REFRESH_TOKEN }}
          repository: neo4j-documentation/docs-refresh
          event-type: labs

  build-s3:
    needs: build-test
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://development.needle-starterkit.graphapp.io/
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: rm -rf docs
      - run: yarn
      - run: yarn run build
      - uses: kersvers/s3-sync-with-cloudfront-invalidation@v1.0.0
        with:
          args: --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
          DISTRIBUTION_ID: ${{ vars.AWS_CDN_ID }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'dist'